"use client";
import Link from "next/link";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { api } from "@/client/api";
import { useLive } from "./LiveProvider";
import type { SetupVersion } from "@/lib/onboarding/types";
type Member = { person_id: string; display_name: string; role: string; removed_at: string | null };
type Choice = { id: string; approved: boolean; detail: "none" | "weekly_note" | "weekly_note_and_record" };
type Topic = { id: string; label: string; contributor_id: string };
export function HouseholdManager() {
  const { session } = useLive(), household = session?.household_id;
  const [people, setPeople] = useState<Member[]>([]), [setup, setSetup] = useState<SetupVersion | null>(null), [topics, setTopics] = useState<Topic[]>([]);
  const [diagnostics, setDiagnostics] = useState<{ web_configured: boolean; scheduler_enabled: boolean; issue: string | null } | null>(null);
  const [webEnabled, setWebEnabled] = useState(false), [channel, setChannel] = useState("dashboard");
  const [choices, setChoices] = useState<Choice[]>([]), [allowed, setAllowed] = useState<string[]>([]), [patientAgreed, setPatientAgreed] = useState(false), [caregiverAgreed, setCaregiverAgreed] = useState(false);
  const [name, setName] = useState(""), [role, setRole] = useState("family"), [label, setLabel] = useState(""), [story, setStory] = useState("");
  const [secret, setSecret] = useState(""), [secretLabel, setSecretLabel] = useState(""), [error, setError] = useState(""), [message, setMessage] = useState(""), [busy, setBusy] = useState(false);
  const base = `/api/onboarding/households/${encodeURIComponent(household ?? "")}`;
  const resetAgreement = () => { setPatientAgreed(false); setCaregiverAgreed(false); };
  const load = useCallback(async () => {
    if (!household) return;
    const [status, nextTopics, liveStatus] = await Promise.all([api<{ people: Member[]; setup: SetupVersion }>(base), api<Topic[]>("/api/onboarding/topics"), api<{ web_configured: boolean; scheduler_enabled: boolean; issue: string | null }>("/api/live/schedule")]);
    setDiagnostics(liveStatus);
    setPeople(status.people.filter((p) => !p.removed_at)); setSetup(status.setup); setTopics(nextTopics);
    const doc = status.setup.document; setWebEnabled(!doc.calls_paused); setChannel(doc.safety.designated_caregivers[0]?.alert_channel ?? "dashboard");
    setChoices(status.people.filter((p) => !p.removed_at && p.role !== "participant").map((p) => ({ id: p.person_id, approved: doc.approved_people.includes(p.person_id), detail: doc.dashboard.grants.find((g) => g.member_id === p.person_id && !g.revoked_at)?.detail_level ?? "none" })));
    setAllowed(doc.topics.allow); resetAgreement();
  }, [base, household]);
  useEffect(() => { void load().catch(() => setError("Household choices could not be loaded.")); }, [load]);
  async function work(fn: () => Promise<void>) { if (busy) return; setBusy(true); setError(""); setMessage(""); try { await fn(); } catch (e) { setError(e instanceof Error ? e.message : "The change could not be saved."); } finally { setBusy(false); } }
  if (!household) return <p><Link href="/onboarding">Complete joint setup first.</Link></p>;
  if (!setup) return <p role="status">{error || "Loading household…"}</p>;
  const caregiver = people.find((p) => p.person_id === setup.document.recall_set_up_by), patient = people.find((p) => p.role === "participant");
  return <section className="recall-onboarding"><Link href="/onboarding">Back to joint setup</Link><h1>People and conversation topics</h1>
    <form className="care-suggestion-form" onSubmit={(e: FormEvent) => { e.preventDefault(); void work(async () => { const r = await api<{ token: string }>(`${base}/invitations`, { method: "POST", body: JSON.stringify({ display_name: name, role, invited_by: caregiver?.person_id }) }); setSecret(r.token); setSecretLabel(`Invitation code for ${name}. Give it to them yourself, along with ${window.location.origin}/join.`); setName(""); }); }}><h2>Invite someone</h2><label>Name<input value={name} onChange={(e) => setName(e.target.value)} maxLength={80} required /></label><label>Role<select value={role} onChange={(e) => setRole(e.target.value)}><option value="family">Family member</option><option value="caregiver">Caregiver</option></select></label><button className="care-action" disabled={busy}>Create invitation</button><p>Joining does not grant access. Review their permissions together after they accept.</p></form>
    <section><h2>Access keys</h2>{people.map((p) => <div key={p.person_id}><p>{p.display_name} · {p.role === "participant" ? "Patient call access" : "Family access"}</p><button className="care-text-action" disabled={busy} onClick={() => void work(async () => { const r = await api<{ key: string }>(`${base}/accounts`, { method: "POST", body: JSON.stringify({ member_id: p.person_id }) }); setSecret(r.key); setSecretLabel(`New access key for ${p.display_name}. Save it privately; their previous key is revoked.`); })}>Issue replacement key</button><button className="care-text-action" disabled={busy} onClick={() => void work(async () => { await api(`${base}/accounts`, { method: "DELETE", body: JSON.stringify({ member_id: p.person_id }) }); setMessage(`Access key revoked for ${p.display_name}.`); setSecret(""); })}>Revoke key</button></div>)}</section>
    {secret && <section role="status"><p>{secretLabel}</p><textarea aria-label="One-time code" readOnly value={secret} /><button className="care-text-action" onClick={() => setSecret("")}>Hide code</button></section>}
    <form className="care-suggestion-form" onSubmit={(e) => { e.preventDefault(); void work(async () => { await api("/api/onboarding/topics", { method: "POST", body: JSON.stringify({ contributor_id: caregiver?.person_id, label, story }) }); setLabel(""); setStory(""); await load(); setMessage("Topic saved as a family contribution. Review its approval below."); }); }}><h2>Add a conversation topic</h2><p>Contributing as {caregiver?.display_name}. This stays their account.</p><label>Short topic name<input required value={label} maxLength={80} onChange={(e) => setLabel(e.target.value)} placeholder="summers at the beach" /></label><label>Your memory<textarea required value={story} maxLength={2000} onChange={(e) => setStory(e.target.value)} /></label><button className="care-action" disabled={busy}>Save topic for review</button></form>
    <form className="care-suggestion-form" onSubmit={(e) => { e.preventDefault(); void work(async () => { await api(`${base}/choices`, { method: "POST", body: JSON.stringify({ expected_version: setup.version, patient_agreed: patientAgreed, caregiver_agreed: caregiverAgreed, members: choices, topics: allowed, web_calls_enabled: webEnabled, alert_channel: channel }) }); await load(); setMessage("Joint choices saved."); }); }}><h2>Review together</h2><fieldset disabled={busy}><legend>Contributions and family view</legend>{choices.map((c) => <div key={c.id}><label><input type="checkbox" checked={c.approved} onChange={(e) => { resetAgreement(); setChoices(choices.map((m) => m.id === c.id ? { ...m, approved: e.target.checked, detail: e.target.checked ? m.detail : "none" } : m)); if (!e.target.checked) setAllowed(allowed.filter((id) => topics.find((t) => t.id === id)?.contributor_id !== c.id)); }} />Approve {people.find((p) => p.person_id === c.id)?.display_name} to contribute</label><label>Family view<select disabled={!c.approved} value={c.detail} onChange={(e) => { resetAgreement(); setChoices(choices.map((m) => m.id === c.id ? { ...m, detail: e.target.value as Choice["detail"] } : m)); }}><option value="none">No dashboard access</option><option value="weekly_note">Weekly Note</option><option value="weekly_note_and_record">Weekly Note and per-topic record</option></select></label></div>)}</fieldset>
    <fieldset disabled={busy}><legend>Topics allowed in future calls</legend>{topics.length === 0 && <p>No topics have been contributed yet.</p>}{topics.map((t) => <label key={t.id}><input type="checkbox" checked={allowed.includes(t.id)} disabled={!choices.some((m) => m.id === t.contributor_id && m.approved)} onChange={(e) => { resetAgreement(); setAllowed(e.target.checked ? [...allowed, t.id] : allowed.filter((id) => id !== t.id)); }} />{t.label}</label>)}</fieldset>
    <fieldset disabled={busy}><legend>Web calls</legend>{diagnostics && <p>{diagnostics.web_configured ? "Voice provider configured." : "Set RECALL_CALL=web and DEEPGRAM_API_KEY on the server."} {diagnostics.scheduler_enabled ? "The schedule worker is enabled." : "Set RECALL_SCHEDULER=1 to check the schedule automatically."}</p>}{diagnostics?.issue && <p role="alert">{diagnostics.issue}</p>}<label><input type="checkbox" checked={webEnabled} onChange={(e) => { resetAgreement(); setWebEnabled(e.target.checked); }} />Enable calls inside the web app during the agreed windows</label><label>Designated caregiver handoff<select value={channel} onChange={(e) => { resetAgreement(); setChannel(e.target.value); }}><option value="dashboard">Caregiver dashboard</option><option value="webhook">Configured caregiver webhook</option></select></label><p>Keep the patient call page open to receive scheduled calls. Recall is not an emergency service.</p></fieldset>
    <label><input type="checkbox" required checked={patientAgreed} onChange={(e) => setPatientAgreed(e.target.checked)} />{patient?.display_name} agrees to these choices.</label><label><input type="checkbox" required checked={caregiverAgreed} onChange={(e) => setCaregiverAgreed(e.target.checked)} />{caregiver?.display_name} agrees to these choices.</label><button className="care-action" disabled={busy}>Save joint choices</button></form>
    {error && <p role="alert" className="setup-error">{error}</p>}<p role="status">{message}</p>
  </section>;
}
